### PR TITLE
update Upperdeck for 2023

### PR DESCRIPTION
**Pull request by generationmake**
lidar is not available any more.
added OpenCyphalPicoBase
new neopixel

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @aentinger 
could you please check if your emerency stop button fits into the central hole? Mine is too big.

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave:

The thread of the emergency stop is M19, so the diameter of the lower hole should be 19 mm (not 22 mm)

Screenshot from 2023-01-14 09-00-00

The length of the threaded area is is ~ 10 mm so the depth (that's currently about 12 mm) should rather be like 6 mm.

Screenshot from 2023-01-14 09-00-09

Link to used emergency stop-button: https://www.conrad.at/de/p/tru-components-not-aus-schalter-3-a-1-oeffner-ip65-1-st-2304759.html

Where shall  the OpenCyphalPicoBase/Aux-Controller be mounted?

**Comment by generationmake** [comment]
Hi @aentinger 
I reworked the data. Could you please check again?
The new idea with the emergency stop is to screw it in directly and not use the nut. So the main hole is 19 mm. I think you can see it in the 3d model and the image.
Do you have a 3d model of the emergency switch?

**Comment by aentinger** [comment]
>Could you please check again?

Did check, looks good now 👍 

>screw it in directly and not use the nut

Good by me 👍 

>Do you have a 3d model of the emergency switch?

Sadly, no. Also did not find one.

**Review by aentinger — APPROVED** [review]

**Comment by aentinger** [comment]
From my perspective all is good. If you give the green light too, I'd start a print run.

**Comment by generationmake** [comment]
yes please do a test print

**Comment by aentinger** [comment]
> yes please do a test print

Print in progress 😁

**Comment by aentinger** [comment]
A little error during printing (probably bad settings) but should do for a prototype fitting:

**Pull request merged**
