### PR TITLE
first idea for #29

### PR DESCRIPTION
**Pull request by scottdarch**
Working with this idea where the compute module is beneath the pan servo (maybe some sort of "dragon beard" aesthetic?)
What's the ground clearance you'll allow here? Alternatively I could put the compute module on the top of the same servo but it might get in the way of your upper-deck sensor package and it might come into the FOV of the optical camera when tilted up.

Please advise.

Note this design gives you ±70º pan, 90º tilt up (look straight up), and 50º tilt down. The optical sensor is located on the tilt access for greater image stability.

### CODE REVIEW

**Comment by scottdarch** [comment]
I'll switch to a branch. I'm queueing the work up in my fork but using draft PRs as a way to structuring an ongoing discussion

**Comment by scottdarch** [comment]
Just an update. I'm vacation for two weeks so I'll have time to finish this, I think. Just waiting on the OpenMV cams for the final test assembly and still designing the cam fixtures.

Here's a test print of the primary structure for the compute unit and the pan axis.

IMG_4106

**Comment by aentinger** [comment]
Looking good 👍 thank you for your effort 🙇 The metallic plate for mounting the tilt servo looks self-made? Or is it one of the Dynamixel back plates?

**Comment by scottdarch** [comment]
> Add more commits by pushing to the `[main](/scottdarch/l3xz-hw)` branch on [scottdarch/l3xz-hw](/scottdarch/l3xz-hw).

Its an [FR07-S101](https://www.robotis.us/fr07-s101-set/?_ga=2.258420938.1772158885.1671525245-1985526878.1670032916). Sorry, I assumed adding this would be okay. It's only $14 USD.

**Comment by aentinger** [comment]
Its perfectly fine 👍 . Probably already in one of my parts boxes, otherwise I'll place an order.

**Comment by scottdarch** [comment]
Question: do you have a smaller servo we could use as the tilt? Using the beefy MX-28AT is overkill for this axis

**Comment by scottdarch** [comment]
Also, I think I'd like to buy the servos for this design. It's sorta a bummer to build the whole thing and not get to actually play with it. Did you say you can get a discount with Dynamixel?

**Comment by scottdarch** [comment]
Also, also: do you want me to accommodate any thermal solutions for the RPi Zero? Heat sinks or fans or anything?

**Comment by aentinger** [comment]
And here's what you need should you want to take your sensor head for a joy(stick) ride:

* [l3xz_joy](https://github.com/107-systems/l3xz_joy): ROS PS3 joystick driver for feeding l3xz_teleop node.
* [l3xz_teleop](https://github.com/107-systems/l3xz_teleop): Teleoperation for L3X-Z via PS3 joystick and ROS topics.
* [l3xz_head_ctrl](https://github.com/107-systems/l3xz_head_ctrl): Head controller for the L3X-Z electric/hydraulic hexapod robot.

**Comment by scottdarch** [comment]
V1 design complete. Starting test prints and assembly now.

I'll close this PR and, once the bugs have been worked out, open a new one from a branch on my fork with the specifications, step files, BOM, and assembly instructions.

Big Rig v10

**Pull request closed without merging**
